### ISSUE TITLE
Incompat with `I&F: RLCraft Edition`

### ISSUE THREAD

**Issue by Krutoy242** [Invadermonky/JustEnoughMagiculture#19]
[Ice & Fire: RLCraft Edition](https://www.curseforge.com/minecraft/mc-mods/iceandfire-rlcraft) is a maintained fork of IceAndFire that adds new features and backport ones implemented in newer MC versions.

I tried to install it on my E2EE modpack and game crashed several times, until I disabled all JEM config options in I&F section.
Crash report:
```ruby
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Just Enough Magiculture (justenoughmagiculture)
Caused by: java.lang.NoClassDefFoundError: com/github/alexthe666/iceandfire/item/IafItemRegistry
    at com.invadermonky.justenoughmagiculture.util.modhelpers.IaFLootHelper$CustomLootDrop.applyIceAndFireFunctions(IaFLootHelper.java:106)
    at com.invadermonky.justenoughmagiculture.util.modhelpers.IaFLootHelper$CustomLootDrop.addLootFunction(IaFLootHelper.java:99)
    at com.invadermonky.justenoughmagiculture.util.modhelpers.IaFLootHelper$CustomLootDrop.lambda$addLootFunctions$0(IaFLootHelper.java:95)
    at java.util.Arrays$ArrayList.forEach(Arrays.java:4266)
    at com.invadermonky.justenoughmagiculture.util.modhelpers.IaFLootHelper$CustomLootDrop.addLootFunctions(IaFLootHelper.java:95)
    at com.invadermonky.justenoughmagiculture.util.modhelpers.IaFLootHelper$CustomLootDrop.addLootFunctions(IaFLootHelper.java:91)
    at com.invadermonky.justenoughmagiculture.util.modhelpers.IaFLootHelper$CustomLootDrop.<init>(IaFLootHelper.java:82)
    at com.invadermonky.justenoughmagiculture.util.modhelpers.IaFLootHelper$CustomLootDrop.<init>(IaFLootHelper.java:86)
    at com.invadermonky.justenoughmagiculture.util.modhelpers.IaFLootHelper.lambda$null$3(IaFLootHelper.java:35)
    at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:215)
```
[crash-2024-11-02_10.48.45-client.txt](https://github.com/user-attachments/files/17606106/crash-2024-11-02_10.48.45-client.txt)

I know its not fail of JEM, since its like RLCraft rewritten lot of classes.

**Comment by Invadermonky** [comment]
I&F: RLCraft Edition is honestly a mess. It's less of a fork and more of a completely new mod. The author changed the location of a huge number of classes effectively breaking compatibility with every Ice and Fire addon.

It is unlikely that I will add support for this fork as it would require rewriting nearly every handler JEM uses for Ice and Fire integration.

**Comment by Krutoy242** [comment]
Its ok, I will not use this fork then.

**Comment by kotlin-programmer** [comment]
> I&F: RLCraft Edition is honestly a mess. It's less of a fork and more of a completely new mod. The author changed the location of a huge number of classes effectively breaking compatibility with every Ice and Fire addon.
> 
> It is unlikely that I will add support for this fork as it would require rewriting nearly every handler JEM uses for Ice and Fire integration.

It's not exactly a completely new mod but rather a fork of an older version of Ice & Fire with some tweaks and changes. That said, I've added better compatibility for mods that are integrated with the latest version of Ice & Fire, such as JustEnoughMagiculture. As such, the new version of Ice & Fire - to be published within the next week - should work with JustEnoughMagiculture without any changes.

**Comment by kotlin-programmer** [comment]
One correction:
Ice & Fire: RLCraft will work as expected with JustEnoughMagiculture in the next update, with the exception of Lightning Dragons. This will however require integration from JustEnoughMagiculture to support.

If this is something that would be of interest to you, checking the Ice & Fire version for Lightning Dragon support is fairly simple. Below is a reference, from the check within the BetterSurvival mod:
https://github.com/mujmajnkraft/BetterSurvival/blob/4f0fc25623fd7c79acd0de63550614f84ceedc05/src/main/java/com/mujmajnkraft/bettersurvival/BetterSurvival.java#L120
