### ISSUE TITLE
Entities like Thaumcraft's `Wisp` not rendered

### ISSUE THREAD

**Issue by Krutoy242** [Invadermonky/JustEnoughMagiculture#3]
In JER tab i cant see any entity rendered in window of entity:

List of entities without render:

**Thaumcraft:**
- Wisp
- Taint Swarm
- Eldritch Guardian
- Eldritch Warden

**Twilight Forest:**
- Firefly

**Ice and Fire:**
- Pet Shop Owner

![image](https://github.com/Invadermonky/JustEnoughMagiculture/assets/936618/4383ab2b-1f79-4b4e-a632-bd6d6f3eb92c)
![image](https://github.com/Invadermonky/JustEnoughMagiculture/assets/936618/4ff88892-0b64-4d07-b003-b12f47b02436)
![image](https://github.com/Invadermonky/JustEnoughMagiculture/assets/936618/b3125765-e605-43e5-9394-2cacb979bde2)
![image](https://github.com/Invadermonky/JustEnoughMagiculture/assets/936618/4fdd51d4-1c5a-43ff-8d29-d5bfeab05c7d)

**Comment by Invadermonky** [comment]
The Wisp, Taint Swarm and Firefly are actually invisible entities that render with particle effects, so the visual representation of these creatures is just particles. Because JER renders a static model of the creatures without the particles, they appear invisible.

There is nothing I can do about this issue without rewriting JER's render code or creating a custom entity for the invisible mobs. If the issue bothers you, you can disable the missing creatures in the JEM config.

As for the Pet Shop Owner, there was some issues with Rats villagers, specifically the Plague Doctor, causing render issues with all other villagers. This required me to do some weird stuff to fix the villagers. If you are using Entity Culling you may want to check to make sure that it is not causing the JER entities to be invisible. This was known to occur with mobs in  Chocolate Quest: Repoured.

What version of Rats are you using and are there any other villagers that are not being displayed?

![image](https://github.com/Invadermonky/JustEnoughMagiculture/assets/101663980/8ec9b255-bca3-4496-ab0d-1abedb677dc5)

**Comment by Krutoy242** [comment]
> If the issue bothers you

No, its not bother me much, i just reported since wasnt sure issue is known.

> other villagers not being displayed?

All other villagers, including Plague Doctor rendered fine.

> make sure that it is not causing the JER entities to be invisible

I do use EC. How to "make sure"?

**Comment by Invadermonky** [comment]
I managed to track down the issue with the Pet Shop Owner.

The Villager Names mod modifies the render code for villagers and causes a NullPointerException when JER attempts to render the Pet Shop Owner. You can see this error spammed in the latest.log while you have the Pet Shop Owner villager trade open in JEI.

```
[00:14:07] [Client thread/ERROR]: Couldn't render entity
java.lang.NullPointerException: null
	at astrotibs.villagenames.client.renderer.entity.RenderVillagerModern.getEntityTexture(RenderVillagerModern.java:113) ~[RenderVillagerModern.class:?]
	at astrotibs.villagenames.client.renderer.entity.RenderVillagerModern.getEntityTexture(RenderVillagerModern.java:22) ~[RenderVillagerModern.class:?]
	at net.minecraft.client.renderer.entity.Render.bindEntityTexture(Render.java:127) ~[bzg.class:?]
	at net.minecraft.client.renderer.entity.RenderLivingBase.renderModel(RenderLivingBase.java:334) ~[caa.class:?]
	at net.minecraft.client.renderer.entity.RenderLivingBase.doRender(RenderLivingBase.java:240) [caa.class:?]
	at net.minecraft.client.renderer.entity.RenderLiving.doRender(RenderLiving.java:50) [caf.class:?]
	at net.minecraft.client.renderer.entity.RenderLiving.doRender(RenderLiving.java:16) [caf.class:?]
	at net.minecraft.client.renderer.entity.RenderManager.laggoggles_trueRender(RenderManager.java:413) [bzf.class:?]
	at com.github.terminatornl.laggoggles.tickcentral.RenderManagerAdapter.redirectRenderEntity(RenderManagerAdapter.java:18) [RenderManagerAdapter.class:1.12.2-5.9-140]
	at net.minecraft.client.renderer.entity.RenderManager.renderEntity(RenderManager.java) [bzf.class:?]
	at jeresources.util.RenderHelper.renderEntity(RenderHelper.java:96) [RenderHelper.class:?]
	at com.invadermonky.justenoughmagiculture.integrations.jei.categories.jer.villager.CustomVillagerWrapper.drawInfo(CustomVillagerWrapper.java:50) [CustomVillagerWrapper.class:?]
	at mezz.jei.gui.recipes.RecipeLayout.drawRecipe(RecipeLayout.java:158) [RecipeLayout.class:?]
	at mezz.jei.gui.recipes.RecipesGui.drawScreen(RecipesGui.java:222) [RecipesGui.class:?]
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396) [ForgeHooksClient.class:?]
	at sun.reflect.GeneratedMethodAccessor56.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.optifine.reflect.Reflector.callVoid(Reflector.java:669) [Reflector.class:?]
	at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1462) [buq.class:?]
	at net.minecraft.client.Minecraft.runGameLoop(MinecraftAccessor.java:1119) [bib.class:?]
	at net.minecraft.client.Minecraft.run(MinecraftAccessor.java:8114) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?] 
```
Unfortunately, this is one of those situations where there is no good fix.

You can disable the Rats villager fix in the JEM config, which will fix the display bug, but it will cause the Plague Doctor to render incorrectly and may cause issues with other villager textures not loading correctly.

Alternatively, you can keep the fix enabled and the Pet Shop Owner will remain invisible and will throw those errors when JER attempts to render the entity.

\
As an aside, since you are looking for issues (which I appreciate) you may notice that the Twilight Forest Frost Queen and the Questing Ram do not have JER pages. Both of these entities caused CTD's when JER attempted to render them and I was unable to fix the issues. The Frost Queen ended up being excluded from JER integration, but I put the Questing Ram rewards in the Dungeon category as a workaround.

**Comment by Krutoy242** [comment]
I will have some play with configurations and report the results.

> Questing Ram

Before JEM i used my own JEI tab for mob drops. I used Draconic Evolution Mob Soul as entity representation. Its rendering mobs, including Questing Ram just fine.
![javaw_SQw0OLg2KV](https://github.com/Invadermonky/JustEnoughMagiculture/assets/936618/47808964-4d79-4656-be1d-89d7f79abcb3)

**Comment by Invadermonky** [comment]
JER entity rendering is... not great. That was part of the reason I stopped adding mods to JEM. About 1 out of every 3 mods required me to rewrite JER handlers and either crowbar them into JER's code or create custom handlers specific to that one situation.

I was having to rewrite entire render code for individual entities just so they wouldn't crash the game or break JER.

**Comment by xJon** [comment]
@Invadermonky You could consider forking JER?

**Comment by Invadermonky** [comment]
Forking JER is kind of a messy topic. The JER license allows for forking, bug fixing and modifying the code but does not explicitly allow redistribution. I would have to rewrite a large chunk of the codebase to fix some of the issues and if I use any of the original JER code, it can be taken down.

In order to avoid the licensing issues I would have to rewrite the entire mod from scratch which would be a massive undertaking.
